### ISSUE TITLE
Enhancement: Comments and Readability of pxelinux.cfg/default

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-srv_tftp#5]
The default is currently generated with some default commands like reboot and poweroff.
One should enhance this file with some valid comments and proper line breaks between the elements.

It is also possible to add more entries like:
- separators
- rescue boot
- boot from disk
- memcheck

**Comment by daniel-schier** [comment]
- rescue boot is somewhat distribution specific
- memtest has another open issue
